message: local

spring:
  datasource:
    url: jdbc:mysql://localhost:33062/test_db?serverTimezone=Asia/Seoul&characterEncoding=UTF-8&useSSL=false
    username: root
    password: root1234
    driver-class-name: com.mysql.cj.jdbc.Driver
    hikari:
      pool-name: TemplateHikariCP
      maximum-pool-size: 10
      minimum-idle: 5
      idle-timeout: 600000         # 10분
      max-lifetime: 1800000        # 30분
      connection-timeout: 30000    # 30초
      auto-commit: true

  jpa:
    hibernate:
      ddl-auto: create       # create, create-drop, update, validate, none
    show-sql: true
    properties:
      hibernate:
        format_sql: true
        dialect: org.hibernate.dialect.MySQL8Dialect
        highlight_sql: true  # Hibernate 6 이상만

cors:
  allowed-origin:
    http://localhost:3000

security:
  public-uris:
    /actuator/**
    , /configuration/security
    , /configuration/ui
    , /swagger-ui/**
    , /swagger-resources/**
    , /v3/api-docs/**
    , /error